version: "3.9"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - default

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/acme.sh:/etc/acme.sh
    networks:
      - default

  backend:
    build: ./backend
    container_name: laravel-api
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql_db
    environment:
      - VIRTUAL_HOST=api.basique-cuisine.site
      - LETSENCRYPT_HOST=api.basique-cuisine.site
      - LETSENCRYPT_EMAIL=tonmail@tondomaine.com
    expose:
      - "80"
    networks:
      - default

  frontend:
    build: ./frontend
    container_name: react-app
    environment:
      - VIRTUAL_HOST=basique-cuisine.site
      - LETSENCRYPT_HOST=basique-cuisine.site
      - LETSENCRYPT_EMAIL=tonmail@tondomaine.com
    expose:
      - "80"
    networks:
      - default

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default

volumes:
  db_data:

networks:
  default:
