services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: basique_cuisine
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/backend
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: basique_cuisine
      DB_USERNAME: root
      DB_PASSWORD: ""
      APP_ENV: production
      APP_KEY: ""  # à générer !
      VIRTUAL_HOST: basique-cuisine.site
      LETSENCRYPT_HOST: basique-cuisine.site
      LETSENCRYPT_EMAIL: lucas.huchede@gmail.com
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: basique-cuisine.site
      LETSENCRYPT_HOST: basique-cuisine.site
      LETSENCRYPT_EMAIL: lucas.huchede@gmail.com
    depends_on:
      - backend

  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      # Si tu veux ajouter ta conf Nginx perso :
      # - ./nginx/custom.conf:/etc/nginx/conf.d/custom.conf:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    environment:
      DEFAULT_EMAIL: lucas.huchede@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

volumes:
  db_data:
