version: "3.9"
services:
  backend:
    build: ./backend
    container_name: laravel-api
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/app
    depends_on:
      - mysql_db

  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - "3000:80"

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
