version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - ./basique_cuisine/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    image: laravelsail/php82-composer
    container_name: backend
    working_dir: /var/www/html
    volumes:
      - ./basique_cuisine/backend:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravelpassword

  frontend:
    image: node:18
    container_name: frontend
    working_dir: /app
    command: sh -c "npm install && npm run build && npx serve -s dist"
    volumes:
      - ./basique_cuisine/frontend:/app
    ports:
      - "5173:3000"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./basique_cuisine/frontend/dist:/usr/share/nginx/html
      - ./basique_cuisine/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
