# docker-compose.yml
services:

  # 1) Base de données MySQL
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: basique_cuisine
      MYSQL_ROOT_PASSWORD: ""    # root sans mot de passe
    volumes:
      - db_data:/var/lib/mysql

  # 2) Backend Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile    # à créer ensuite
    restart: unless-stopped
    working_dir: /var/www/backend
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: basique_cuisine
      DB_USERNAME: root
      DB_PASSWORD: ""
      APP_ENV: production
      # Générer votre clé : `php artisan key:generate --show`
      APP_KEY: ""
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      - db

  # 3) Frontend React/Vite
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile    # à créer ensuite
    restart: unless-stopped
    # Ce service va juste builder votre app et produire le dossier `dist/`

  # 4) Nginx : sert le front statique et reverse-proxy vers Laravel
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./backend/public:/var/www/backend/public:ro
      - certs:/etc/letsencrypt
      - certs-data:/var/lib/letsencrypt
    depends_on:
      - backend

volumes:
  db_data:
  certs:
  certs-data:
