version: "3.9"
services:
  backend:
    build: ./backend
    container_name: laravel-api
    volumes:
      - ./backend:/var/www/app
    depends_on:
      - mysql_db
    environment:
      - VIRTUAL_HOST=api.basique-cuisine.site
      - LETSENCRYPT_HOST=api.basique-cuisine.site
      - LETSENCRYPT_EMAIL=tonemail@example.com
    networks:
      - default

  frontend:
    build: ./frontend
    container_name: react-app
    environment:
      - VIRTUAL_HOST=basique-cuisine.site
      - LETSENCRYPT_HOST=basique-cuisine.site
      - LETSENCRYPT_EMAIL=tonemail@example.com
    networks:
      - default

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
