name: 🚀 Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/basique_cuisine
          git pull origin main
          docker-compose down
          docker-compose up -d --build

    - name: 🔍 Lancer les tests sur le serveur distant
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
        "cd /var/www/basique_cuisine && [ -x ./run-tests.sh ] && ./run-tests.sh || echo 'Aucun test trouvé.'"
